Feature/input
woxox/woxox-ui pull request #16
Opened 2024-02-08 15:16 UTC by WhiteKr

2024-02-08 15:20 UTC, Heavyrisem requested changes

2024-02-08 15:20 UTC, Heavyrisem commented on packages/woxox-ui/src/components/atoms/Input/index.tsx
> +      <Text style={{ ...baseToken.fontSize[12] }}>{label}</Text>
Text에 fontSize 조절하는 프롭 있으면 그걸로 사용

2024-02-08 15:20 UTC, Heavyrisem commented on packages/woxox-ui/src/components/atoms/Input/input.css.ts
> +        borderColor: colorToken['background.input'],
border 색상에 background 사용하지 말고, 새 color token 생성하는건 어떤지?
비 직관적인 문제가 있어보임

2024-02-08 15:26 UTC, WhiteKr commented on packages/woxox-ui/src/components/atoms/Input/index.tsx
> +      <Text style={{ ...baseToken.fontSize[12] }}>{label}</Text>
@Heavyrisem 
그럼 `fontSize`와 `fontWeight`를 각각 적용해야하는건가요?
아니면 태그 안에서도 spread가 되나

2024-02-08 15:38 UTC, Heavyrisem commented on packages/woxox-ui/src/components/atoms/Input/index.tsx
> +      <Text style={{ ...baseToken.fontSize[12] }}>{label}</Text>
`fontSize` `fontWeight`는 묶을 수 없는 속성이라 둘이 분리해서 구현한걸로 확인되었고
Text 컴포넌트 사용은
```tsx
<Text fontSize="14" fontWeight="medium" />
```
처럼 하면 됨

2024-02-08 15:39 UTC, WhiteKr commented on packages/woxox-ui/src/components/atoms/Input/index.tsx
> +      <Text style={{ ...baseToken.fontSize[12] }}>{label}</Text>
아아 ㄱㅅㄱㅅ fontWeight가 아니라 lineHeight였음 헷갈림.
지금 보니까 fontSize 속성 주면 알아서 lineHeight도 쌍에 맞게 먹게끔 되어있는거 확인함

2024-02-11 03:33 UTC, Heavyrisem requested changes
LGTM~
focus 스타일 추가해주세요

2024-02-11 11:41 UTC, merged